var _ang = angle;
var _xo = sin(_ang / 180 * pi) * angle_dist;
var _yo = cos(_ang / 180 * pi) * angle_dist;
var _spr_ind = (angle_dist != angle_dist_max ? ((angle_dist / angle_dist_max) * 4) : (timer / 5 mod 5) + 4);
draw_sprite(sprite_index, _spr_ind, x + _xo, y + _yo);
_ang += 90;
_xo = sin(_ang / 180 * pi) * angle_dist;
_yo = cos(_ang / 180 * pi) * angle_dist;
draw_sprite(sprite_index, _spr_ind, x + _xo, y + _yo);
_ang += 90;
_xo = sin(_ang / 180 * pi) * angle_dist;
_yo = cos(_ang / 180 * pi) * angle_dist;
draw_sprite(sprite_index, _spr_ind, x + _xo, y + _yo);
_ang += 90;
_xo = sin(_ang / 180 * pi) * angle_dist;
_yo = cos(_ang / 180 * pi) * angle_dist;
draw_sprite(sprite_index, _spr_ind, x + _xo, y + _yo);

_spr_ind = (angle_dist != angle_dist_max ? ((angle_dist / angle_dist_max) * 4 ) : 9);
_ang += 45;
_xo = sin(_ang / 180 * pi) * angle_dist;
_yo = cos(_ang / 180 * pi) * angle_dist;
draw_sprite(sprite_index, _spr_ind, x + _xo, y + _yo);
_ang += 90;
_xo = sin(_ang / 180 * pi) * angle_dist;
_yo = cos(_ang / 180 * pi) * angle_dist;
draw_sprite(sprite_index, _spr_ind, x + _xo, y + _yo);
_ang += 90;
_xo = sin(_ang / 180 * pi) * angle_dist;
_yo = cos(_ang / 180 * pi) * angle_dist;
draw_sprite(sprite_index, _spr_ind, x + _xo, y + _yo);
_ang += 90;
_xo = sin(_ang / 180 * pi) * angle_dist;
_yo = cos(_ang / 180 * pi) * angle_dist;
draw_sprite(sprite_index, _spr_ind, x + _xo, y + _yo);